const perfumes = [
  {
    id: 1,
    name: "Dior Sauvage",
    brand: "Dior",
    gender: ["Male", "Unisex"],
    ageGroup: ["18-25", "26-35", "36-45"],
    moods: ["Bold", "Energetic"],
    outfit: ["Casual", "Street", "Formal"],
    season: ["Summer", "Autumn", "Winter"],
    time: ["Evening", "Night", "Midnight"],
    intensity: "Strong",
    occasions: ["Party", "Date Night"],
    notes: "Pepper, bergamot, amberwood",
    longevity: "Long",
    sillage: "Strong",
    image: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=400"
  },
  {
    id: 2,
    name: "Black Opium",
    brand: "YSL",
    gender: ["Female", "Unisex"],
    ageGroup: ["18-25", "26-35"],
    moods: ["Bold", "Sensual"],
    outfit: ["Glam", "Party", "Formal"],
    season: ["Autumn", "Winter"],
    time: ["Night", "Midnight"],
    intensity: "Strong",
    occasions: ["Party", "Date Night"],
    notes: "Coffee, vanilla, jasmine",
    longevity: "Long",
    sillage: "Strong",
    image: "https://images.unsplash.com/photo-1619613798346-8d4e6e9d8bca?w=400"
  },
  {
    id: 3,
    name: "Chanel No. 5",
    brand: "Chanel",
    gender: ["Female"],
    ageGroup: ["26-35", "36-45", "45+"],
    moods: ["Elegant"],
    outfit: ["Formal", "Classic"],
    season: ["Winter", "Autumn"],
    time: ["Evening"],
    intensity: "Medium",
    occasions: ["Wedding", "Formal Event"],
    notes: "Aldehydes, jasmine, rose",
    longevity: "Long",
    sillage: "Moderate",
    image: "https://images.unsplash.com/photo-1541643600914-78b084683601?w=400"
  },
  {
    id: 4,
    name: "Bleu de Chanel",
    brand: "Chanel",
    gender: ["Male", "Unisex"],
    ageGroup: ["18-25", "26-35", "36-45"],
    moods: ["Elegant", "Fresh"],
    outfit: ["Formal", "Casual"],
    season: ["All"],
    time: ["Morning", "Evening"],
    intensity: "Medium",
    occasions: ["Office", "Date Night"],
    notes: "Citrus, incense, cedarwood",
    longevity: "Long",
    sillage: "Moderate",
    image: "https://images.unsplash.com/photo-1587017539504-67cfbddac569?w=400"
  },
  {
    id: 5,
    name: "Good Girl",
    brand: "Carolina Herrera",
    gender: ["Female"],
    ageGroup: ["18-25", "26-35"],
    moods: ["Sensual", "Bold"],
    outfit: ["Glam", "Formal"],
    season: ["Autumn", "Winter"],
    time: ["Night"],
    intensity: "Strong",
    occasions: ["Party", "Date Night"],
    notes: "Tonka bean, jasmine, cacao",
    longevity: "Very Long",
    sillage: "Strong",
    image: "https://images.unsplash.com/photo-1600185365528-3950ca30be7a?w=400"
  },
  {
    id: 6,
    name: "Versace Eros",
    brand: "Versace",
    gender: ["Male"],
    ageGroup: ["18-25"],
    moods: ["Energetic", "Bold"],
    outfit: ["Party", "Street"],
    season: ["Winter", "Autumn"],
    time: ["Night"],
    intensity: "Strong",
    occasions: ["Party"],
    notes: "Mint, vanilla, tonka bean",
    longevity: "Long",
    sillage: "Strong",
    image: "https://images.unsplash.com/photo-1594035910387-fea47794261f?w=400"
  },
  {
    id: 7,
    name: "Miss Dior Blooming Bouquet",
    brand: "Dior",
    gender: ["Female"],
    ageGroup: ["18-25", "26-35"],
    moods: ["Soft", "Elegant"],
    outfit: ["Casual", "Chic"],
    season: ["Spring", "Summer"],
    time: ["Morning", "Afternoon"],
    intensity: "Light",
    occasions: ["Brunch", "Day Out"],
    notes: "Peony, rose, musk",
    longevity: "Moderate",
    sillage: "Soft",
    image: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=400"
  },
  {
    id: 8,
    name: "Armani Si",
    brand: "Giorgio Armani",
    gender: ["Female"],
    ageGroup: ["26-35"],
    moods: ["Elegant", "Sensual"],
    outfit: ["Chic", "Formal"],
    season: ["Autumn", "Winter"],
    time: ["Evening"],
    intensity: "Medium",
    occasions: ["Formal Event"],
    notes: "Blackcurrant, rose, vanilla",
    longevity: "Long",
    sillage: "Moderate",
    image: "https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=400"
  },
  {
    id: 9,
    name: "Luna Rossa Ocean",
    brand: "Prada",
    gender: ["Male", "Unisex"],
    ageGroup: ["18-25", "26-35"],
    moods: ["Fresh", "Clean"],
    outfit: ["Casual", "Office"],
    season: ["Summer"],
    time: ["Morning", "Afternoon"],
    intensity: "Medium",
    occasions: ["Office", "Day Use"],
    notes: "Bergamot, iris, vetiver",
    longevity: "Moderate",
    sillage: "Soft",
    image: "https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?w=400"
  },
  {
    id: 10,
    name: "Oud Wood",
    brand: "Tom Ford",
    gender: ["Male", "Female", "Unisex"],
    ageGroup: ["26-35", "36-45", "45+"],
    moods: ["Mysterious", "Elegant"],
    outfit: ["Formal", "Luxury"],
    season: ["Autumn", "Winter"],
    time: ["Night"],
    intensity: "Strong",
    occasions: ["Formal Event", "Special Occasion"],
    notes: "Oud, amber, sandalwood",
    longevity: "Very Long",
    sillage: "Strong",
    image: "https://images.unsplash.com/photo-1594035910387-fea47794261f?w=400"
  },

  // ---- 11 to 25 below ----

  {
    id: 11,
    name: "Light Blue",
    brand: "Dolce & Gabbana",
    gender: ["Female", "Unisex"],
    ageGroup: ["18-25", "26-35"],
    moods: ["Energetic", "Fresh"],
    outfit: ["Casual", "Beach"],
    season: ["Summer"],
    time: ["Morning", "Afternoon"],
    intensity: "Light",
    occasions: ["Day Out"],
    notes: "Citrus, green apple, cedar",
    longevity: "Moderate",
    sillage: "Soft",
    image: "https://images.unsplash.com/photo-1509941091028-6f28f5d0c2c1?w=400"
  },
  {
    id: 12,
    name: "La Vie Est Belle",
    brand: "Lancome",
    gender: ["Female"],
    ageGroup: ["26-35", "36-45"],
    moods: ["Elegant", "Soft"],
    outfit: ["Formal", "Chic"],
    season: ["Autumn", "Winter"],
    time: ["Evening"],
    intensity: "Medium",
    occasions: ["Formal Event"],
    notes: "Iris, praline, vanilla",
    longevity: "Long",
    sillage: "Strong",
    image: "https://images.unsplash.com/photo-1611080626919-b03c8800bd90?w=400"
  },
  {
    id: 13,
    name: "Aventus",
    brand: "Creed",
    gender: ["Male", "Unisex"],
    ageGroup: ["26-35", "36-45"],
    moods: ["Bold", "Confident"],
    outfit: ["Formal", "Luxury"],
    season: ["All"],
    time: ["Evening"],
    intensity: "Strong",
    occasions: ["Business", "Special Occasion"],
    notes: "Pineapple, birch, musk",
    longevity: "Very Long",
    sillage: "Strong",
    image: "https://images.unsplash.com/photo-1618384242246-9abb5d545ed4?w=400"
  },
  {
    id: 14,
    name: "Chance Eau Tendre",
    brand: "Chanel",
    gender: ["Female"],
    ageGroup: ["18-25", "26-35"],
    moods: ["Soft", "Fresh"],
    outfit: ["Casual", "Chic"],
    season: ["Spring", "Summer"],
    time: ["Morning"],
    intensity: "Light",
    occasions: ["Day Out"],
    notes: "Grapefruit, jasmine, musk",
    longevity: "Moderate",
    sillage: "Soft",
    image: "https://images.unsplash.com/photo-1618498082443-616165d8f3c4?w=400"
  },
  {
    id: 15,
    name: "Flowerbomb",
    brand: "Viktor&Rolf",
    gender: ["Female"],
    ageGroup: ["18-25", "26-35"],
    moods: ["Bold", "Elegant"],
    outfit: ["Glam"],
    season: ["Autumn", "Winter"],
    time: ["Evening"],
    intensity: "Strong",
    occasions: ["Party", "Event"],
    notes: "Jasmine, rose, patchouli",
    longevity: "Long",
    sillage: "Strong",
    image: "https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=400"
  },
  {
    id: 16,
    name: "Club de Nuit Intense",
    brand: "Armaf",
    gender: ["Male"],
    ageGroup: ["18-25", "26-35"],
    moods: ["Bold"],
    outfit: ["Street", "Formal"],
    season: ["Autumn", "Winter"],
    time: ["Night"],
    intensity: "Strong",
    occasions: ["Party"],
    notes: "Lemon, pineapple, birch",
    longevity: "Very Long",
    sillage: "Strong",
    image: "https://images.unsplash.com/photo-1587017539504-67cfbddac569?w=400"
  },
  {
    id: 17,
    name: "My Way",
    brand: "Giorgio Armani",
    gender: ["Female"],
    ageGroup: ["18-25", "26-35"],
    moods: ["Soft", "Elegant"],
    outfit: ["Casual", "Chic"],
    season: ["Spring", "Summer"],
    time: ["Morning", "Afternoon"],
    intensity: "Medium",
    occasions: ["Day Out"],
    notes: "Orange blossom, vanilla, cedarwood",
    longevity: "Moderate",
    sillage: "Soft",
    image: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=400"
  },
  {
    id: 18,
    name: "Initio Side Effect",
    brand: "Initio",
    gender: ["Unisex"],
    ageGroup: ["26-35", "36-45"],
    moods: ["Mysterious", "Sensual"],
    outfit: ["Luxury", "Night"],
    season: ["Autumn", "Winter"],
    time: ["Night"],
    intensity: "Strong",
    occasions: ["Special Occasion"],
    notes: "Rum, tobacco, vanilla",
    longevity: "Very Long",
    sillage: "Huge",
    image: "https://images.unsplash.com/photo-1611080626919-b03c8800bd90?w=400"
  },
  {
    id: 19,
    name: "Bright Crystal",
    brand: "Versace",
    gender: ["Female"],
    ageGroup: ["18-25"],
    moods: ["Fresh", "Soft"],
    outfit: ["Casual"],
    season: ["Spring", "Summer"],
    time: ["Morning"],
    intensity: "Light",
    occasions: ["Day Out"],
    notes: "Pomegranate, lotus, amber",
    longevity: "Moderate",
    sillage: "Soft",
    image: "https://images.unsplash.com/photo-1509941091028-6f28f5d0c2c1?w=400"
  },
  {
    id: 20,
    name: "Terre d'Hermès",
    brand: "Hermès",
    gender: ["Male"],
    ageGroup: ["26-35", "36-45"],
    moods: ["Elegant", "Fresh"],
    outfit: ["Formal"],
    season: ["Autumn", "Spring"],
    time: ["Morning"],
    intensity: "Medium",
    occasions: ["Office"],
    notes: "Orange, vetiver, cedar",
    longevity: "Long",
    sillage: "Moderate",
    image: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=400"
  },
  {
    id: 21,
    name: "Aqua di Gio",
    brand: "Giorgio Armani",
    gender: ["Male"],
    ageGroup: ["18-25", "26-35"],
    moods: ["Fresh", "Clean"],
    outfit: ["Casual"],
    season: ["Summer"],
    time: ["Morning"],
    intensity: "Light",
    occasions: ["Day Use"],
    notes: "Citrus, sea notes, jasmine",
    longevity: "Moderate",
    sillage: "Soft",
    image: "https://images.unsplash.com/photo-1589654316003-657d2dbe0a3c?w=400"
  },
  {
    id: 22,
    name: "Cloud",
    brand: "Ariana Grande",
    gender: ["Female"],
    ageGroup: ["18-25"],
    moods: ["Soft", "Sweet"],
    outfit: ["Casual"],
    season: ["All"],
    time: ["Morning", "Afternoon"],
    intensity: "Light",
    occasions: ["Day Use"],
    notes: "Lavender, pear, whipped cream",
    longevity: "Moderate",
    sillage: "Soft",
    image: "https://images.unsplash.com/photo-1619613798346-8d4e6e9d8bca?w=400"
  },
  {
    id: 23,
    name: "Olympéa",
    brand: "Paco Rabanne",
    gender: ["Female"],
    ageGroup: ["18-25", "26-35"],
    moods: ["Bold", "Fresh"],
    outfit: ["Chic"],
    season: ["Autumn"],
    time: ["Evening"],
    intensity: "Medium",
    occasions: ["Date Night"],
    notes: "Salt, vanilla, ambergris",
    longevity: "Long",
    sillage: "Strong",
    image: "https://images.unsplash.com/photo-1611080626919-b03c8800bd90?w=400"
  },
  {
    id: 24,
    name: "Pure XS",
    brand: "Paco Rabanne",
    gender: ["Male"],
    ageGroup: ["18-25"],
    moods: ["Energetic", "Bold"],
    outfit: ["Street", "Party"],
    season: ["Winter"],
    time: ["Night"],
    intensity: "Strong",
    occasions: ["Party"],
    notes: "Vanilla, ginger, myrrh",
    longevity: "Long",
    sillage: "Strong",
    image: "https://images.unsplash.com/photo-1594035910387-fea47794261f?w=400"
  },
  {
    id: 25,
    name: "Valentino Donna Born in Roma",
    brand: "Valentino",
    gender: ["Female"],
    ageGroup: ["18-25", "26-35"],
    moods: ["Bold", "Chic"],
    outfit: ["Glam"],
    season: ["Autumn", "Winter"],
    time: ["Night"],
    intensity: "Strong",
    occasions: ["Party"],
    notes: "Blackcurrant, jasmine, vanilla",
    longevity: "Very Long",
    sillage: "Strong",
    image: "https://images.unsplash.com/photo-1541643600914-78b084683601?w=400"
  },
  // =========================
// PERFUMES 26 – 50
// =========================

  {
    id: 26,
    name: "YSL Libre",
    brand: "YSL",
    gender: ["Female"],
    ageGroup: ["18-25", "26-35", "36-45"],
    moods: ["Bold", "Elegant"],
    outfit: ["Formal", "Glam"],
    season: ["Autumn", "Winter"],
    time: ["Evening", "Night"],
    intensity: "Strong",
    occasions: ["Formal Event", "Party"],
    notes: "Lavender, orange blossom, vanilla",
    longevity: "Long",
    sillage: "Strong",
    image: "https://images.unsplash.com/photo-1600185365528-3950ca30be7a?w=400"
  },
  {
    id: 27,
    name: "Armani Code",
    brand: "Giorgio Armani",
    gender: ["Male"],
    ageGroup: ["26-35", "36-45"],
    moods: ["Elegant", "Sensual"],
    outfit: ["Formal"],
    season: ["Autumn", "Winter"],
    time: ["Night"],
    intensity: "Medium",
    occasions: ["Date Night"],
    notes: "Tonka bean, tobacco, leather",
    longevity: "Long",
    sillage: "Moderate",
    image: "https://images.unsplash.com/photo-1589654316003-657d2dbe0a3c?w=400"
  },
  {
    id: 28,
    name: "Mugler Alien",
    brand: "Mugler",
    gender: ["Female"],
    ageGroup: ["18-25", "26-35"],
    moods: ["Bold", "Mysterious"],
    outfit: ["Glam", "Night"],
    season: ["Autumn", "Winter"],
    time: ["Night"],
    intensity: "Strong",
    occasions: ["Party", "Event"],
    notes: "Jasmine, amber, wood",
    longevity: "Very Long",
    sillage: "Huge",
    image: "https://images.unsplash.com/photo-1611080626919-b03c8800bd90?w=400"
  },
  {
    id: 29,
    name: "Gucci Bloom",
    brand: "Gucci",
    gender: ["Female"],
    ageGroup: ["18-25", "26-35"],
    moods: ["Elegant", "Soft"],
    outfit: ["Boho", "Chic"],
    season: ["Spring"],
    time: ["Morning"],
    intensity: "Light",
    occasions: ["Brunch", "Day Out"],
    notes: "Tuberose, jasmine, rangoon creeper",
    longevity: "Moderate",
    sillage: "Soft",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400"
  },
  {
    id: 30,
    name: "Tom Ford Black Orchid",
    brand: "Tom Ford",
    gender: ["Unisex"],
    ageGroup: ["26-35", "36-45"],
    moods: ["Mysterious", "Bold"],
    outfit: ["Luxury", "Evening"],
    season: ["Autumn", "Winter"],
    time: ["Night"],
    intensity: "Very Strong",
    occasions: ["Special Event"],
    notes: "Black truffle, patchouli, incense",
    longevity: "Very Long",
    sillage: "Huge",
    image: "https://images.unsplash.com/photo-1594035910387-fea47794261f?w=400"
  },
  {
    id: 31,
    name: "Burberry Her",
    brand: "Burberry",
    gender: ["Female"],
    ageGroup: ["18-25"],
    moods: ["Soft", "Sweet"],
    outfit: ["Casual"],
    season: ["Spring", "Summer"],
    time: ["Afternoon", "Morning"],
    intensity: "Medium",
    occasions: ["Day Out"],
    notes: "Strawberry, raspberry, musk",
    longevity: "Long",
    sillage: "Moderate",
    image: "https://images.unsplash.com/photo-1619613798346-8d4e6e9d8bca?w=400"
  },
  {
    id: 32,
    name: "Boss Bottled",
    brand: "Hugo Boss",
    gender: ["Male"],
    ageGroup: ["18-25", "26-35"],
    moods: ["Fresh", "Confident"],
    outfit: ["Office", "Casual"],
    season: ["All"],
    time: ["Morning"],
    intensity: "Medium",
    occasions: ["Office", "Work"],
    notes: "Apple, cinnamon, sandalwood",
    longevity: "Moderate",
    sillage: "Soft",
    image: "https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?w=400"
  },
  {
    id: 33,
    name: "J’adore",
    brand: "Dior",
    gender: ["Female"],
    ageGroup: ["26-35", "36-45"],
    moods: ["Elegant"],
    outfit: ["Formal", "Classic"],
    season: ["Spring", "Autumn"],
    time: ["Evening"],
    intensity: "Medium",
    occasions: ["Formal Event"],
    notes: "Ylang-ylang, jasmine, rose",
    longevity: "Moderate",
    sillage: "Soft",
    image: "https://images.unsplash.com/photo-1618498082443-616165d8f3c4?w=400"
  },
  {
    id: 34,
    name: "Fahrenheit",
    brand: "Dior",
    gender: ["Male"],
    ageGroup: ["26-35", "36-45"],
    moods: ["Bold", "Mysterious"],
    outfit: ["Street", "Luxury"],
    season: ["Autumn"],
    time: ["Night"],
    intensity: "Strong",
    occasions: ["Night Out"],
    notes: "Leather, violet, nutmeg",
    longevity: "Long",
    sillage: "Strong",
    image: "https://images.unsplash.com/photo-1541643600914-78b084683601?w=400"
  },
  {
    id: 35,
    name: "Mont Blanc Explorer",
    brand: "Mont Blanc",
    gender: ["Male"],
    ageGroup: ["18-25", "26-35"],
    moods: ["Elegant", "Fresh"],
    outfit: ["Office", "Casual"],
    season: ["All"],
    time: ["Morning", "Evening"],
    intensity: "Medium",
    occasions: ["Work"],
    notes: "Bergamot, vetiver, patchouli",
    longevity: "Long",
    sillage: "Moderate",
    image: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=400"
  },
  {
    id: 36,
    name: "Dolce Garden",
    brand: "Dolce & Gabbana",
    gender: ["Female"],
    ageGroup: ["18-25", "26-35"],
    moods: ["Soft", "Fresh"],
    outfit: ["Casual", "Chic"],
    season: ["Spring", "Summer"],
    time: ["Morning"],
    intensity: "Light",
    occasions: ["Brunch"],
    notes: "Coconut, frangipani, vanilla",
    longevity: "Moderate",
    sillage: "Soft",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400"
  },
  {
    id: 37,
    name: "Replica Jazz Club",
    brand: "Maison Margiela",
    gender: ["Unisex"],
    ageGroup: ["26-35", "36-45"],
    moods: ["Mysterious", "Warm"],
    outfit: ["Street", "Night"],
    season: ["Autumn", "Winter"],
    time: ["Night"],
    intensity: "Medium",
    occasions: ["Night Out"],
    notes: "Rum, tobacco, vanilla",
    longevity: "Long",
    sillage: "Moderate",
    image: "https://images.unsplash.com/photo-1594035910387-fea47794261f?w=400"
  },
  {
    id: 38,
    name: "Armani Acqua Di Gioia",
    brand: "Giorgio Armani",
    gender: ["Female"],
    ageGroup: ["18-25", "26-35"],
    moods: ["Fresh", "Soft"],
    outfit: ["Casual"],
    season: ["Summer"],
    time: ["Morning", "Afternoon"],
    intensity: "Light",
    occasions: ["Beach"],
    notes: "Lemon, mint, jasmine",
    longevity: "Moderate",
    sillage: "Soft",
    image: "https://images.unsplash.com/photo-1618384242246-9abb5d545ed4?w=400"
  },
  {
    id: 39,
    name: "Narciso Rodriguez For Her",
    brand: "Narciso Rodriguez",
    gender: ["Female"],
    ageGroup: ["26-35", "36-45"],
    moods: ["Elegant"],
    outfit: ["Formal", "Chic"],
    season: ["Autumn"],
    time: ["Evening"],
    intensity: "Medium",
    occasions: ["Formal Event"],
    notes: "Musk, rose, amber",
    longevity: "Moderate",
    sillage: "Moderate",
    image: "https://images.unsplash.com/photo-1618498082443-616165d8f3c4?w=400"
  },
  {
    id: 40,
    name: "Bad Boy",
    brand: "Carolina Herrera",
    gender: ["Male"],
    ageGroup: ["18-25", "26-35"],
    moods: ["Bold", "Energetic"],
    outfit: ["Street"],
    season: ["Winter"],
    time: ["Night"],
    intensity: "Strong",
    occasions: ["Party"],
    notes: "Pepper, tonka bean, cacao",
    longevity: "Long",
    sillage: "Strong",
    image: "https://images.unsplash.com/photo-1600185365528-3950ca30be7a?w=400"
  },
  {
    id: 41,
    name: "Tobacco Vanille",
    brand: "Tom Ford",
    gender: ["Unisex"],
    ageGroup: ["26-35", "36-45"],
    moods: ["Warm", "Sensual"],
    outfit: ["Luxury"],
    season: ["Winter"],
    time: ["Night"],
    intensity: "Very Strong",
    occasions: ["Special Occasion"],
    notes: "Tobacco, vanilla, spices",
    longevity: "Very Long",
    sillage: "Huge",
    image: "https://images.unsplash.com/photo-1611080626919-b03c8800bd90?w=400"
  },
  {
    id: 42,
    name: "Dolce Rose",
    brand: "D&G",
    gender: ["Female"],
    ageGroup: ["18-25"],
    moods: ["Soft", "Fresh"],
    outfit: ["Casual"],
    season: ["Spring"],
    time: ["Morning"],
    intensity: "Light",
    occasions: ["Brunch"],
    notes: "Red berries, rose, musk",
    longevity: "Moderate",
    sillage: "Soft",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400"
  },
  {
    id: 43,
    name: "Spicebomb Extreme",
    brand: "Viktor&Rolf",
    gender: ["Male"],
    ageGroup: ["26-35"],
    moods: ["Bold", "Warm"],
    outfit: ["Street", "Night"],
    season: ["Winter"],
    time: ["Night"],
    intensity: "Strong",
    occasions: ["Party"],
    notes: "Vanilla, tobacco, cinnamon",
    longevity: "Very Long",
    sillage: "Huge",
    image: "https://images.unsplash.com/photo-1611080626919-b03c8800bd90?w=400"
  },
  {
    id: 44,
    name: "Idôle",
    brand: "Lancôme",
    gender: ["Female"],
    ageGroup: ["18-25", "26-35"],
    moods: ["Elegant", "Fresh"],
    outfit: ["Casual", "Chic"],
    season: ["Spring", "Autumn"],
    time: ["Morning"],
    intensity: "Light",
    occasions: ["Day Use"],
    notes: "Rose, jasmine, musk",
    longevity: "Moderate",
    sillage: "Soft",
    image: "https://images.unsplash.com/photo-1618498082443-616165d8f3c4?w=400"
  },
  {
    id: 45,
    name: "Cool Water",
    brand: "Davidoff",
    gender: ["Male"],
    ageGroup: ["18-25"],
    moods: ["Fresh", "Energetic"],
    outfit: ["Casual", "Beach"],
    season: ["Summer"],
    time: ["Morning"],
    intensity: "Light",
    occasions: ["Outdoor"],
    notes: "Mint, seawater, lavender",
    longevity: "Moderate",
    sillage: "Soft",
    image: "https://images.unsplash.com/photo-1589654316003-657d2dbe0a3c?w=400"
  },
  {
    id: 46,
    name: "Guess Seductive",
    brand: "Guess",
    gender: ["Female"],
    ageGroup: ["18-25"],
    moods: ["Sensual", "Soft"],
    outfit: ["Party", "Chic"],
    season: ["Summer"],
    time: ["Evening"],
    intensity: "Light",
    occasions: ["Night Out"],
    notes: "Pear, jasmine, vanilla",
    longevity: "Moderate",
    sillage: "Moderate",
    image: "https://images.unsplash.com/photo-1509941091028-6f28f5d0c2c1?w=400"
  },
  {
    id: 47,
    name: "212 Men",
    brand: "Carolina Herrera",
    gender: ["Male"],
    ageGroup: ["18-25", "26-35"],
    moods: ["Fresh", "Confident"],
    outfit: ["Casual", "Office"],
    season: ["Spring"],
    time: ["Morning"],
    intensity: "Medium",
    occasions: ["Office"],
    notes: "Grapefruit, spices, wood",
    longevity: "Moderate",
    sillage: "Moderate",
    image: "https://images.unsplash.com/photo-1587017539504-67cfbddac569?w=400"
  },
  {
    id: 48,
    name: "Jimmy Choo Blossom",
    brand: "Jimmy Choo",
    gender: ["Female"],
    ageGroup: ["18-25"],
    moods: ["Fresh", "Soft"],
    outfit: ["Casual"],
    season: ["Spring"],
    time: ["Morning"],
    intensity: "Light",
    occasions: ["Day Out"],
    notes: "Raspberry, rose, musk",
    longevity: "Moderate",
    sillage: "Soft",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400"
  },
  {
    id: 49,
    name: "Givenchy Gentleman",
    brand: "Givenchy",
    gender: ["Male"],
    ageGroup: ["26-35", "36-45"],
    moods: ["Elegant"],
    outfit: ["Formal"],
    season: ["Winter"],
    time: ["Evening"],
    intensity: "Strong",
    occasions: ["Formal Event"],
    notes: "Vanilla, iris, patchouli",
    longevity: "Very Long",
    sillage: "Strong",
    image: "https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?w=400"
  },
  {
    id: 50,
    name: "Versace Dylan Blue",
    brand: "Versace",
    gender: ["Male"],
    ageGroup: ["18-25", "26-35"],
    moods: ["Confident", "Fresh"],
    outfit: ["Street", "Casual"],
    season: ["Autumn", "Winter"],
    time: ["Evening"],
    intensity: "Medium",
    occasions: ["Night Out"],
    notes: "Grapefruit, fig leaves, patchouli",
    longevity: "Long",
    sillage: "Moderate",
    image: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=400"
  },
// =========================
// PERFUMES 51 – 75
// =========================

  {
    id: 51,
    name: "Jean Paul Gaultier Le Male",
    brand: "Jean Paul Gaultier",
    gender: ["Male"],
    ageGroup: ["18-25", "26-35"],
    moods: ["Bold", "Warm"],
    outfit: ["Street", "Party"],
    season: ["Winter", "Autumn"],
    time: ["Night", "Evening"],
    intensity: "Strong",
    occasions: ["Night Out"],
    notes: "Mint, lavender, vanilla",
    longevity: "Long",
    sillage: "Strong",
    image: "https://images.unsplash.com/photo-1589654316003-657d2dbe0a3c?w=400"
  },
  {
    id: 52,
    name: "Marc Jacobs Daisy",
    brand: "Marc Jacobs",
    gender: ["Female"],
    ageGroup: ["18-25"],
    moods: ["Soft", "Fresh"],
    outfit: ["Casual"],
    season: ["Spring", "Summer"],
    time: ["Morning"],
    intensity: "Light",
    occasions: ["Day Out"],
    notes: "Strawberry, violet leaves, jasmine",
    longevity: "Moderate",
    sillage: "Soft",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400"
  },
  {
    id: 53,
    name: "Tom Ford Soleil Blanc",
    brand: "Tom Ford",
    gender: ["Unisex"],
    ageGroup: ["25-35", "36-45"],
    moods: ["Fresh", "Elegant"],
    outfit: ["Beach", "Luxury"],
    season: ["Summer"],
    time: ["Morning", "Afternoon"],
    intensity: "Medium",
    occasions: ["Vacation"],
    notes: "Coconut, bergamot, amber",
    longevity: "Moderate",
    sillage: "Moderate",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400"
  },
  {
    id: 54,
    name: "Gucci Guilty Pour Homme",
    brand: "Gucci",
    gender: ["Male"],
    ageGroup: ["18-25", "26-35"],
    moods: ["Bold", "Energetic"],
    outfit: ["Street", "Night"],
    season: ["Winter", "Autumn"],
    time: ["Night"],
    intensity: "Medium",
    occasions: ["Party"],
    notes: "Lavender, lemon, patchouli",
    longevity: "Moderate",
    sillage: "Moderate",
    image: "https://images.unsplash.com/photo-1611080626919-b03c8800bd90?w=400"
  },
  {
    id: 55,
    name: "Gucci Guilty Pour Femme",
    brand: "Gucci",
    gender: ["Female"],
    ageGroup: ["18-25"],
    moods: ["Sensual", "Bold"],
    outfit: ["Glam", "Night"],
    season: ["Winter"],
    time: ["Night"],
    intensity: "Medium",
    occasions: ["Party"],
    notes: "Mandora, lilac, patchouli",
    longevity: "Long",
    sillage: "Strong",
    image: "https://images.unsplash.com/photo-1600185365528-3950ca30be7a?w=400"
  },
  {
    id: 56,
    name: "Nautica Voyage",
    brand: "Nautica",
    gender: ["Male"],
    ageGroup: ["18-25"],
    moods: ["Fresh", "Clean"],
    outfit: ["Casual", "Beach"],
    season: ["Summer"],
    time: ["Morning"],
    intensity: "Light",
    occasions: ["Outdoor"],
    notes: "Apple, lotus, musk",
    longevity: "Moderate",
    sillage: "Soft",
    image: "https://images.unsplash.com/photo-1587017539504-67cfbddac569?w=400"
  },
  {
    id: 57,
    name: "Prada Paradoxe",
    brand: "Prada",
    gender: ["Female"],
    ageGroup: ["18-25", "26-35"],
    moods: ["Elegant", "Sweet"],
    outfit: ["Casual", "Chic"],
    season: ["Spring"],
    time: ["Morning", "Afternoon"],
    intensity: "Medium",
    occasions: ["Brunch"],
    notes: "Musk, neroli, vanilla",
    longevity: "Long",
    sillage: "Moderate",
    image: "https://images.unsplash.com/photo-1618384242246-9abb5d545ed4?w=400"
  },
  {
    id: 58,
    name: "Maison Francis Kurkdjian Baccarat Rouge 540",
    brand: "MFK",
    gender: ["Unisex"],
    ageGroup: ["26-35", "36-45"],
    moods: ["Elegant", "Mysterious"],
    outfit: ["Luxury"],
    season: ["All"],
    time: ["Night"],
    intensity: "Strong",
    occasions: ["Special Event"],
    notes: "Saffron, ambergris, cedar",
    longevity: "Very Long",
    sillage: "Huge",
    image: "https://images.unsplash.com/photo-1594035910387-fea47794261f?w=400"
  },
  {
    id: 59,
    name: "Mugler Angel",
    brand: "Mugler",
    gender: ["Female"],
    ageGroup: ["26-35"],
    moods: ["Bold", "Glam"],
    outfit: ["Night", "Chic"],
    season: ["Winter"],
    time: ["Night"],
    intensity: "Very Strong",
    occasions: ["Party"],
    notes: "Patchouli, praline, bergamot",
    longevity: "Very Long",
    sillage: "Huge",
    image: "https://images.unsplash.com/photo-1611080626919-b03c8800bd90?w=400"
  },
  {
    id: 60,
    name: "Acqua di Parma Colonia",
    brand: "Acqua di Parma",
    gender: ["Unisex"],
    ageGroup: ["26-35", "36-45", "45+"],
    moods: ["Fresh", "Elegant"],
    outfit: ["Formal"],
    season: ["Spring", "Summer"],
    time: ["Morning", "Afternoon"],
    intensity: "Light",
    occasions: ["Office", "Day Use"],
    notes: "Citrus, lavender, rosemary",
    longevity: "Moderate",
    sillage: "Soft",
    image: "https://images.unsplash.com/photo-1585421514284-efb74c2b7961?w=400"
  },
  {
    id: 61,
    name: "Dolce & Gabbana The One",
    brand: "D&G",
    gender: ["Male"],
    ageGroup: ["26-35", "36-45"],
    moods: ["Warm", "Elegant"],
    outfit: ["Formal", "Night"],
    season: ["Autumn", "Winter"],
    time: ["Evening"],
    intensity: "Medium",
    occasions: ["Date Night"],
    notes: "Tobacco, amber, ginger",
    longevity: "Long",
    sillage: "Moderate",
    image: "https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?w=400"
  },
  {
    id: 62,
    name: "Jo Malone Peony & Blush Suede",
    brand: "Jo Malone",
    gender: ["Female"],
    ageGroup: ["26-35", "36-45"],
    moods: ["Elegant", "Soft"],
    outfit: ["Formal", "Chic"],
    season: ["Spring"],
    time: ["Morning"],
    intensity: "Light",
    occasions: ["Brunch"],
    notes: "Peony, red apple, suede",
    longevity: "Moderate",
    sillage: "Soft",
    image: "https://images.unsplash.com/photo-1509941091028-6f28f5d0c2c1?w=400"
  },
  {
    id: 63,
    name: "Memo Irish Leather",
    brand: "Memo",
    gender: ["Unisex"],
    ageGroup: ["26-35", "36-45"],
    moods: ["Mysterious", "Bold"],
    outfit: ["Luxury"],
    season: ["Winter"],
    time: ["Night"],
    intensity: "Very Strong",
    occasions: ["Special Occasion"],
    notes: "Leather, juniper, amber",
    longevity: "Very Long",
    sillage: "Huge",
    image: "https://images.unsplash.com/photo-1594035910387-fea47794261f?w=400"
  },
  {
    id: 64,
    name: "Bvlgari Omnia Crystalline",
    brand: "Bvlgari",
    gender: ["Female"],
    ageGroup: ["18-25", "26-35"],
    moods: ["Fresh", "Soft"],
    outfit: ["Casual"],
    season: ["Summer", "Spring"],
    time: ["Morning"],
    intensity: "Light",
    occasions: ["Day Use"],
    notes: "Pear, bamboo, lotus",
    longevity: "Moderate",
    sillage: "Soft",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400"
  },
  {
    id: 65,
    name: "Creed Green Irish Tweed",
    brand: "Creed",
    gender: ["Male"],
    ageGroup: ["26-35", "36-45"],
    moods: ["Fresh", "Elegant"],
    outfit: ["Formal"],
    season: ["Spring", "Summer"],
    time: ["Morning"],
    intensity: "Medium",
    occasions: ["Office"],
    notes: "Lemon, mint, ambergris",
    longevity: "Long",
    sillage: "Moderate",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400"
  },
  {
    id: 66,
    name: "Montale Intense Café",
    brand: "Montale",
    gender: ["Unisex"],
    ageGroup: ["26-35"],
    moods: ["Sensual", "Warm"],
    outfit: ["Night"],
    season: ["Winter"],
    time: ["Night"],
    intensity: "Very Strong",
    occasions: ["Date Night"],
    notes: "Coffee, rose, vanilla",
    longevity: "Very Long",
    sillage: "Huge",
    image: "https://images.unsplash.com/photo-1600185365528-3950ca30be7a?w=400"
  },
  {
    id: 67,
    name: "Zara Femme",
    brand: "Zara",
    gender: ["Female"],
    ageGroup: ["18-25"],
    moods: ["Soft", "Elegant"],
    outfit: ["Casual"],
    season: ["Spring"],
    time: ["Morning"],
    intensity: "Light",
    occasions: ["Day Use"],
    notes: "Vanilla, peony, musk",
    longevity: "Moderate",
    sillage: "Soft",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400"
  },
  {
    id: 68,
    name: "Armani Stronger With You",
    brand: "Giorgio Armani",
    gender: ["Male"],
    ageGroup: ["18-25", "26-35"],
    moods: ["Warm", "Sensual"],
    outfit: ["Street", "Night"],
    season: ["Winter", "Autumn"],
    time: ["Night"],
    intensity: "Strong",
    occasions: ["Date Night"],
    notes: "Vanilla, cardamom, chestnut",
    longevity: "Very Long",
    sillage: "Strong",
    image: "https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?w=400"
  },
  {
    id: 69,
    name: "YSL Mon Paris",
    brand: "YSL",
    gender: ["Female"],
    ageGroup: ["18-25"],
    moods: ["Romantic", "Soft"],
    outfit: ["Chic"],
    season: ["Spring", "Summer"],
    time: ["Morning"],
    intensity: "Light",
    occasions: ["Date", "Day Out"],
    notes: "Strawberry, jasmine, patchouli",
    longevity: "Moderate",
    sillage: "Moderate",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400"
  },
  {
    id: 70,
    name: "Dolce & Gabbana K",
    brand: "D&G",
    gender: ["Male"],
    ageGroup: ["26-35", "18-25"],
    moods: ["Confident", "Fresh"],
    outfit: ["Casual", "Street"],
    season: ["Summer"],
    time: ["Afternoon"],
    intensity: "Medium",
    occasions: ["Day Out"],
    notes: "Citrus, juniper, cedar",
    longevity: "Moderate",
    sillage: "Moderate",
    image: "https://images.unsplash.com/photo-1589654316003-657d2dbe0a3c?w=400"
  },
  {
    id: 71,
    name: "Hugo Boss The Scent",
    brand: "Hugo Boss",
    gender: ["Male"],
    ageGroup: ["18-25", "26-35"],
    moods: ["Warm", "Sensual"],
    outfit: ["Night"],
    season: ["Winter"],
    time: ["Night"],
    intensity: "Medium",
    occasions: ["Date Night"],
    notes: "Ginger, maninka fruit, leather",
    longevity: "Moderate",
    sillage: "Moderate",
    image: "https://images.unsplash.com/photo-1611080626919-b03c8800bd90?w=400"
  },
  {
    id: 72,
    name: "Zara Vibrant Leather",
    brand: "Zara",
    gender: ["Male"],
    ageGroup: ["18-25"],
    moods: ["Fresh", "Elegant"],
    outfit: ["Casual"],
    season: ["Summer"],
    time: ["Morning"],
    intensity: "Light",
    occasions: ["Day Out"],
    notes: "Bergamot, leather, amber",
    longevity: "Moderate",
    sillage: "Soft",
    image: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=400"
  },
  {
    id: 73,
    name: "Maison Margiela Beach Walk",
    brand: "Replica",
    gender: ["Female"],
    ageGroup: ["18-25", "26-35"],
    moods: ["Fresh", "Soft"],
    outfit: ["Beach"],
    season: ["Summer"],
    time: ["Morning"],
    intensity: "Light",
    occasions: ["Beach"],
    notes: "Coconut, bergamot, musk",
    longevity: "Moderate",
    sillage: "Soft",
    image: "https://images.unsplash.com/photo-1509941091028-6f28f5d0c2c1?w=400"
  },
  {
    id: 74,
    name: "Calvin Klein Euphoria",
    brand: "Calvin Klein",
    gender: ["Female"],
    ageGroup: ["26-35"],
    moods: ["Sensual", "Bold"],
    outfit: ["Night", "Chic"],
    season: ["Winter"],
    time: ["Night"],
    intensity: "Strong",
    occasions: ["Date Night"],
    notes: "Pomegranate, orchid, mahogany",
    longevity: "Long",
    sillage: "Strong",
    image: "https://images.unsplash.com/photo-1618498082443-616165d8f3c4?w=400"
  },
  {
    id: 75,
    name: "John Varvatos Vintage",
    brand: "John Varvatos",
    gender: ["Male"],
    ageGroup: ["26-35", "36-45"],
    moods: ["Warm", "Elegant"],
    outfit: ["Formal"],
    season: ["Autumn"],
    time: ["Evening"],
    intensity: "Medium",
    occasions: ["Dinner"],
    notes: "Tobacco, cinnamon, suede",
    longevity: "Moderate",
    sillage: "Moderate",
    image: "https://images.unsplash.com/photo-1594035910387-fea47794261f?w=400"
  },
// =========================
// PERFUMES 51 – 75
// =========================

  {
    id: 51,
    name: "Jean Paul Gaultier Le Male",
    brand: "Jean Paul Gaultier",
    gender: ["Male"],
    ageGroup: ["18-25", "26-35"],
    moods: ["Bold", "Warm"],
    outfit: ["Street", "Party"],
    season: ["Winter", "Autumn"],
    time: ["Night", "Evening"],
    intensity: "Strong",
    occasions: ["Night Out"],
    notes: "Mint, lavender, vanilla",
    longevity: "Long",
    sillage: "Strong",
    image: "https://images.unsplash.com/photo-1589654316003-657d2dbe0a3c?w=400"
  },
  {
    id: 52,
    name: "Marc Jacobs Daisy",
    brand: "Marc Jacobs",
    gender: ["Female"],
    ageGroup: ["18-25"],
    moods: ["Soft", "Fresh"],
    outfit: ["Casual"],
    season: ["Spring", "Summer"],
    time: ["Morning"],
    intensity: "Light",
    occasions: ["Day Out"],
    notes: "Strawberry, violet leaves, jasmine",
    longevity: "Moderate",
    sillage: "Soft",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400"
  },
  {
    id: 53,
    name: "Tom Ford Soleil Blanc",
    brand: "Tom Ford",
    gender: ["Unisex"],
    ageGroup: ["25-35", "36-45"],
    moods: ["Fresh", "Elegant"],
    outfit: ["Beach", "Luxury"],
    season: ["Summer"],
    time: ["Morning", "Afternoon"],
    intensity: "Medium",
    occasions: ["Vacation"],
    notes: "Coconut, bergamot, amber",
    longevity: "Moderate",
    sillage: "Moderate",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400"
  },
  {
    id: 54,
    name: "Gucci Guilty Pour Homme",
    brand: "Gucci",
    gender: ["Male"],
    ageGroup: ["18-25", "26-35"],
    moods: ["Bold", "Energetic"],
    outfit: ["Street", "Night"],
    season: ["Winter", "Autumn"],
    time: ["Night"],
    intensity: "Medium",
    occasions: ["Party"],
    notes: "Lavender, lemon, patchouli",
    longevity: "Moderate",
    sillage: "Moderate",
    image: "https://images.unsplash.com/photo-1611080626919-b03c8800bd90?w=400"
  },
  {
    id: 55,
    name: "Gucci Guilty Pour Femme",
    brand: "Gucci",
    gender: ["Female"],
    ageGroup: ["18-25"],
    moods: ["Sensual", "Bold"],
    outfit: ["Glam", "Night"],
    season: ["Winter"],
    time: ["Night"],
    intensity: "Medium",
    occasions: ["Party"],
    notes: "Mandora, lilac, patchouli",
    longevity: "Long",
    sillage: "Strong",
    image: "https://images.unsplash.com/photo-1600185365528-3950ca30be7a?w=400"
  },
  {
    id: 56,
    name: "Nautica Voyage",
    brand: "Nautica",
    gender: ["Male"],
    ageGroup: ["18-25"],
    moods: ["Fresh", "Clean"],
    outfit: ["Casual", "Beach"],
    season: ["Summer"],
    time: ["Morning"],
    intensity: "Light",
    occasions: ["Outdoor"],
    notes: "Apple, lotus, musk",
    longevity: "Moderate",
    sillage: "Soft",
    image: "https://images.unsplash.com/photo-1587017539504-67cfbddac569?w=400"
  },
  {
    id: 57,
    name: "Prada Paradoxe",
    brand: "Prada",
    gender: ["Female"],
    ageGroup: ["18-25", "26-35"],
    moods: ["Elegant", "Sweet"],
    outfit: ["Casual", "Chic"],
    season: ["Spring"],
    time: ["Morning", "Afternoon"],
    intensity: "Medium",
    occasions: ["Brunch"],
    notes: "Musk, neroli, vanilla",
    longevity: "Long",
    sillage: "Moderate",
    image: "https://images.unsplash.com/photo-1618384242246-9abb5d545ed4?w=400"
  },
  {
    id: 58,
    name: "Maison Francis Kurkdjian Baccarat Rouge 540",
    brand: "MFK",
    gender: ["Unisex"],
    ageGroup: ["26-35", "36-45"],
    moods: ["Elegant", "Mysterious"],
    outfit: ["Luxury"],
    season: ["All"],
    time: ["Night"],
    intensity: "Strong",
    occasions: ["Special Event"],
    notes: "Saffron, ambergris, cedar",
    longevity: "Very Long",
    sillage: "Huge",
    image: "https://images.unsplash.com/photo-1594035910387-fea47794261f?w=400"
  },
  {
    id: 59,
    name: "Mugler Angel",
    brand: "Mugler",
    gender: ["Female"],
    ageGroup: ["26-35"],
    moods: ["Bold", "Glam"],
    outfit: ["Night", "Chic"],
    season: ["Winter"],
    time: ["Night"],
    intensity: "Very Strong",
    occasions: ["Party"],
    notes: "Patchouli, praline, bergamot",
    longevity: "Very Long",
    sillage: "Huge",
    image: "https://images.unsplash.com/photo-1611080626919-b03c8800bd90?w=400"
  },
  {
    id: 60,
    name: "Acqua di Parma Colonia",
    brand: "Acqua di Parma",
    gender: ["Unisex"],
    ageGroup: ["26-35", "36-45", "45+"],
    moods: ["Fresh", "Elegant"],
    outfit: ["Formal"],
    season: ["Spring", "Summer"],
    time: ["Morning", "Afternoon"],
    intensity: "Light",
    occasions: ["Office", "Day Use"],
    notes: "Citrus, lavender, rosemary",
    longevity: "Moderate",
    sillage: "Soft",
    image: "https://images.unsplash.com/photo-1585421514284-efb74c2b7961?w=400"
  },
  {
    id: 61,
    name: "Dolce & Gabbana The One",
    brand: "D&G",
    gender: ["Male"],
    ageGroup: ["26-35", "36-45"],
    moods: ["Warm", "Elegant"],
    outfit: ["Formal", "Night"],
    season: ["Autumn", "Winter"],
    time: ["Evening"],
    intensity: "Medium",
    occasions: ["Date Night"],
    notes: "Tobacco, amber, ginger",
    longevity: "Long",
    sillage: "Moderate",
    image: "https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?w=400"
  },
  {
    id: 62,
    name: "Jo Malone Peony & Blush Suede",
    brand: "Jo Malone",
    gender: ["Female"],
    ageGroup: ["26-35", "36-45"],
    moods: ["Elegant", "Soft"],
    outfit: ["Formal", "Chic"],
    season: ["Spring"],
    time: ["Morning"],
    intensity: "Light",
    occasions: ["Brunch"],
    notes: "Peony, red apple, suede",
    longevity: "Moderate",
    sillage: "Soft",
    image: "https://images.unsplash.com/photo-1509941091028-6f28f5d0c2c1?w=400"
  },
  {
    id: 63,
    name: "Memo Irish Leather",
    brand: "Memo",
    gender: ["Unisex"],
    ageGroup: ["26-35", "36-45"],
    moods: ["Mysterious", "Bold"],
    outfit: ["Luxury"],
    season: ["Winter"],
    time: ["Night"],
    intensity: "Very Strong",
    occasions: ["Special Occasion"],
    notes: "Leather, juniper, amber",
    longevity: "Very Long",
    sillage: "Huge",
    image: "https://images.unsplash.com/photo-1594035910387-fea47794261f?w=400"
  },
  {
    id: 64,
    name: "Bvlgari Omnia Crystalline",
    brand: "Bvlgari",
    gender: ["Female"],
    ageGroup: ["18-25", "26-35"],
    moods: ["Fresh", "Soft"],
    outfit: ["Casual"],
    season: ["Summer", "Spring"],
    time: ["Morning"],
    intensity: "Light",
    occasions: ["Day Use"],
    notes: "Pear, bamboo, lotus",
    longevity: "Moderate",
    sillage: "Soft",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400"
  },
  {
    id: 65,
    name: "Creed Green Irish Tweed",
    brand: "Creed",
    gender: ["Male"],
    ageGroup: ["26-35", "36-45"],
    moods: ["Fresh", "Elegant"],
    outfit: ["Formal"],
    season: ["Spring", "Summer"],
    time: ["Morning"],
    intensity: "Medium",
    occasions: ["Office"],
    notes: "Lemon, mint, ambergris",
    longevity: "Long",
    sillage: "Moderate",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400"
  },
  {
    id: 66,
    name: "Montale Intense Café",
    brand: "Montale",
    gender: ["Unisex"],
    ageGroup: ["26-35"],
    moods: ["Sensual", "Warm"],
    outfit: ["Night"],
    season: ["Winter"],
    time: ["Night"],
    intensity: "Very Strong",
    occasions: ["Date Night"],
    notes: "Coffee, rose, vanilla",
    longevity: "Very Long",
    sillage: "Huge",
    image: "https://images.unsplash.com/photo-1600185365528-3950ca30be7a?w=400"
  },
  {
    id: 67,
    name: "Zara Femme",
    brand: "Zara",
    gender: ["Female"],
    ageGroup: ["18-25"],
    moods: ["Soft", "Elegant"],
    outfit: ["Casual"],
    season: ["Spring"],
    time: ["Morning"],
    intensity: "Light",
    occasions: ["Day Use"],
    notes: "Vanilla, peony, musk",
    longevity: "Moderate",
    sillage: "Soft",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400"
  },
  {
    id: 68,
    name: "Armani Stronger With You",
    brand: "Giorgio Armani",
    gender: ["Male"],
    ageGroup: ["18-25", "26-35"],
    moods: ["Warm", "Sensual"],
    outfit: ["Street", "Night"],
    season: ["Winter", "Autumn"],
    time: ["Night"],
    intensity: "Strong",
    occasions: ["Date Night"],
    notes: "Vanilla, cardamom, chestnut",
    longevity: "Very Long",
    sillage: "Strong",
    image: "https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?w=400"
  },
  {
    id: 69,
    name: "YSL Mon Paris",
    brand: "YSL",
    gender: ["Female"],
    ageGroup: ["18-25"],
    moods: ["Romantic", "Soft"],
    outfit: ["Chic"],
    season: ["Spring", "Summer"],
    time: ["Morning"],
    intensity: "Light",
    occasions: ["Date", "Day Out"],
    notes: "Strawberry, jasmine, patchouli",
    longevity: "Moderate",
    sillage: "Moderate",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400"
  },
  {
    id: 70,
    name: "Dolce & Gabbana K",
    brand: "D&G",
    gender: ["Male"],
    ageGroup: ["26-35", "18-25"],
    moods: ["Confident", "Fresh"],
    outfit: ["Casual", "Street"],
    season: ["Summer"],
    time: ["Afternoon"],
    intensity: "Medium",
    occasions: ["Day Out"],
    notes: "Citrus, juniper, cedar",
    longevity: "Moderate",
    sillage: "Moderate",
    image: "https://images.unsplash.com/photo-1589654316003-657d2dbe0a3c?w=400"
  },
  {
    id: 71,
    name: "Hugo Boss The Scent",
    brand: "Hugo Boss",
    gender: ["Male"],
    ageGroup: ["18-25", "26-35"],
    moods: ["Warm", "Sensual"],
    outfit: ["Night"],
    season: ["Winter"],
    time: ["Night"],
    intensity: "Medium",
    occasions: ["Date Night"],
    notes: "Ginger, maninka fruit, leather",
    longevity: "Moderate",
    sillage: "Moderate",
    image: "https://images.unsplash.com/photo-1611080626919-b03c8800bd90?w=400"
  },
  {
    id: 72,
    name: "Zara Vibrant Leather",
    brand: "Zara",
    gender: ["Male"],
    ageGroup: ["18-25"],
    moods: ["Fresh", "Elegant"],
    outfit: ["Casual"],
    season: ["Summer"],
    time: ["Morning"],
    intensity: "Light",
    occasions: ["Day Out"],
    notes: "Bergamot, leather, amber",
    longevity: "Moderate",
    sillage: "Soft",
    image: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=400"
  },
  {
    id: 73,
    name: "Maison Margiela Beach Walk",
    brand: "Replica",
    gender: ["Female"],
    ageGroup: ["18-25", "26-35"],
    moods: ["Fresh", "Soft"],
    outfit: ["Beach"],
    season: ["Summer"],
    time: ["Morning"],
    intensity: "Light",
    occasions: ["Beach"],
    notes: "Coconut, bergamot, musk",
    longevity: "Moderate",
    sillage: "Soft",
    image: "https://images.unsplash.com/photo-1509941091028-6f28f5d0c2c1?w=400"
  },
  {
    id: 74,
    name: "Calvin Klein Euphoria",
    brand: "Calvin Klein",
    gender: ["Female"],
    ageGroup: ["26-35"],
    moods: ["Sensual", "Bold"],
    outfit: ["Night", "Chic"],
    season: ["Winter"],
    time: ["Night"],
    intensity: "Strong",
    occasions: ["Date Night"],
    notes: "Pomegranate, orchid, mahogany",
    longevity: "Long",
    sillage: "Strong",
    image: "https://images.unsplash.com/photo-1618498082443-616165d8f3c4?w=400"
  },
  {
    id: 75,
    name: "John Varvatos Vintage",
    brand: "John Varvatos",
    gender: ["Male"],
    ageGroup: ["26-35", "36-45"],
    moods: ["Warm", "Elegant"],
    outfit: ["Formal"],
    season: ["Autumn"],
    time: ["Evening"],
    intensity: "Medium",
    occasions: ["Dinner"],
    notes: "Tobacco, cinnamon, suede",
    longevity: "Moderate",
    sillage: "Moderate",
    image: "https://images.unsplash.com/photo-1594035910387-fea47794261f?w=400"
  },
// =========================
// PERFUMES 76 – 100
// =========================

  {
    id: 76,
    name: "Azzaro Wanted",
    brand: "Azzaro",
    gender: ["Male"],
    ageGroup: ["18-25", "26-35"],
    moods: ["Energetic", "Bold"],
    outfit: ["Street", "Party"],
    season: ["Summer", "Autumn"],
    time: ["Night"],
    intensity: "Strong",
    occasions: ["Party"],
    notes: "Lemon, cardamom, tonka bean",
    longevity: "Long",
    sillage: "Strong",
    image: "https://images.unsplash.com/photo-1611080626919-b03c8800bd90?w=400"
  },
  {
    id: 77,
    name: "Carolina Herrera Very Good Girl",
    brand: "Carolina Herrera",
    gender: ["Female"],
    ageGroup: ["18-25", "26-35"],
    moods: ["Bold", "Romantic"],
    outfit: ["Chic", "Night"],
    season: ["Winter", "Autumn"],
    time: ["Night"],
    intensity: "Medium",
    occasions: ["Date"],
    notes: "Red currant, lychee, rose",
    longevity: "Moderate",
    sillage: "Moderate",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400"
  },
  {
    id: 78,
    name: "Rasasi Hawas",
    brand: "Rasasi",
    gender: ["Male"],
    ageGroup: ["18-25", "26-35"],
    moods: ["Fresh", "Sporty"],
    outfit: ["Casual"],
    season: ["Summer"],
    time: ["Morning"],
    intensity: "Medium",
    occasions: ["Day Out"],
    notes: "Cinnamon, bergamot, ambergris",
    longevity: "Long",
    sillage: "Moderate",
    image: "https://images.unsplash.com/photo-1600185365528-3950ca30be7a?w=400"
  },
  {
    id: 79,
    name: "Valentino Donna Born in Roma",
    brand: "Valentino",
    gender: ["Female"],
    ageGroup: ["18-25", "26-35"],
    moods: ["Sensual", "Elegant"],
    outfit: ["Glam"],
    season: ["Autumn", "Winter"],
    time: ["Night"],
    intensity: "Medium",
    occasions: ["Night Out"],
    notes: "Blackcurrant, jasmine, bourbon vanilla",
    longevity: "Long",
    sillage: "Moderate",
    image: "https://images.unsplash.com/photo-1618498082443-616165d8f3c4?w=400"
  },
  {
    id: 80,
    name: "Lattafa Asad",
    brand: "Lattafa",
    gender: ["Male"],
    ageGroup: ["18-25"],
    moods: ["Warm", "Sensual"],
    outfit: ["Night"],
    season: ["Winter"],
    time: ["Night"],
    intensity: "Strong",
    occasions: ["Date"],
    notes: "Vanilla, pepper, patchouli",
    longevity: "Very Long",
    sillage: "Strong",
    image: "https://images.unsplash.com/photo-1594035910387-fea47794261f?w=400"
  },
  {
    id: 81,
    name: "Mont Blanc Legend Spirit",
    brand: "Mont Blanc",
    gender: ["Male"],
    ageGroup: ["18-25"],
    moods: ["Fresh", "Clean"],
    outfit: ["Casual"],
    season: ["Summer"],
    time: ["Morning"],
    intensity: "Light",
    occasions: ["College", "Daily"],
    notes: "Grapefruit, lavender, oakmoss",
    longevity: "Moderate",
    sillage: "Soft",
    image: "https://images.unsplash.com/photo-1589654316003-657d2dbe0a3c?w=400"
  },
  {
    id: 82,
    name: "Chanel Chance Eau Tendre",
    brand: "Chanel",
    gender: ["Female"],
    ageGroup: ["18-25", "26-35"],
    moods: ["Soft", "Romantic"],
    outfit: ["Chic"],
    season: ["Spring"],
    time: ["Morning"],
    intensity: "Light",
    occasions: ["Brunch"],
    notes: "Grapefruit, jasmine, white musk",
    longevity: "Moderate",
    sillage: "Soft",
    image: "https://images.unsplash.com/photo-1509941091028-6f28f5d0c2c1?w=400"
  },
  {
    id: 83,
    name: "Paco Rabanne Fame",
    brand: "Paco Rabanne",
    gender: ["Female"],
    ageGroup: ["18-25"],
    moods: ["Energetic", "Chic"],
    outfit: ["Trendy"],
    season: ["Summer", "Spring"],
    time: ["Afternoon"],
    intensity: "Medium",
    occasions: ["Outing"],
    notes: "Mango, jasmine, vanilla",
    longevity: "Moderate",
    sillage: "Moderate",
    image: "https://images.unsplash.com/photo-1525695230005-efd074980869?w=400"
  },
  {
    id: 84,
    name: "Ajmal Aristocrat",
    brand: "Ajmal",
    gender: ["Female"],
    ageGroup: ["26-35"],
    moods: ["Elegant", "Formal"],
    outfit: ["Formal"],
    season: ["Winter", "Autumn"],
    time: ["Evening"],
    intensity: "Medium",
    occasions: ["Special Event"],
    notes: "Musk, amber, floral notes",
    longevity: "Long",
    sillage: "Moderate",
    image: "https://images.unsplash.com/photo-1585421514284-efb74c2b7961?w=400"
  },
  {
    id: 85,
    name: "Bentley for Men Intense",
    brand: "Bentley",
    gender: ["Male"],
    ageGroup: ["26-35", "36-45"],
    moods: ["Strong", "Warm"],
    outfit: ["Formal", "Night"],
    season: ["Winter"],
    time: ["Night"],
    intensity: "Very Strong",
    occasions: ["Special Event"],
    notes: "Rum, cinnamon, leather",
    longevity: "Very Long",
    sillage: "Huge",
    image: "https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?w=400"
  },
  {
    id: 86,
    name: "Versace Pour Homme",
    brand: "Versace",
    gender: ["Male"],
    ageGroup: ["18-25", "26-35"],
    moods: ["Fresh", "Clean"],
    outfit: ["Casual"],
    season: ["Summer"],
    time: ["Morning"],
    intensity: "Light",
    occasions: ["Daily"],
    notes: "Citrus, neroli, musk",
    longevity: "Moderate",
    sillage: "Moderate",
    image: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=400"
  },
  {
    id: 87,
    name: "Swiss Arabian Shaghaf Oud",
    brand: "Swiss Arabian",
    gender: ["Unisex"],
    ageGroup: ["26-35", "36-45"],
    moods: ["Warm", "Sensual"],
    outfit: ["Night"],
    season: ["Winter"],
    time: ["Night"],
    intensity: "Very Strong",
    occasions: ["Special Event"],
    notes: "Oud, rose, praline",
    longevity: "Very Long",
    sillage: "Huge",
    image: "https://images.unsplash.com/photo-1600185365528-3950ca30be7a?w=400"
  },
  {
    id: 88,
    name: "Issey Miyake L’Eau d’Issey",
    brand: "Issey Miyake",
    gender: ["Female"],
    ageGroup: ["18-25", "26-35"],
    moods: ["Fresh", "Elegant"],
    outfit: ["Minimal"],
    season: ["Spring"],
    time: ["Morning"],
    intensity: "Light",
    occasions: ["Office"],
    notes: "Lotus, melon, musk",
    longevity: "Moderate",
    sillage: "Soft",
    image: "https://images.unsplash.com/photo-1589654316003-657d2dbe0a3c?w=400"
  },
  {
    id: 89,
    name: "Rasasi Blue for Men",
    brand: "Rasasi",
    gender: ["Male"],
    ageGroup: ["18-25"],
    moods: ["Clean", "Fresh"],
    outfit: ["Casual"],
    season: ["Summer"],
    time: ["Morning"],
    intensity: "Light",
    occasions: ["College"],
    notes: "Mint, lavender, amber",
    longevity: "Moderate",
    sillage: "Soft",
    image: "https://images.unsplash.com/photo-1509941091028-6f28f5d0c2c1?w=400"
  },
  {
    id: 90,
    name: "Calvin Klein Eternity",
    brand: "Calvin Klein",
    gender: ["Female"],
    ageGroup: ["26-35"],
    moods: ["Soft", "Elegant"],
    outfit: ["Formal"],
    season: ["Spring"],
    time: ["Morning"],
    intensity: "Light",
    occasions: ["Office"],
    notes: "Lily, mandarin, jasmine",
    longevity: "Moderate",
    sillage: "Soft",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400"
  },
  {
    id: 91,
    name: "David Beckham Homme",
    brand: "David Beckham",
    gender: ["Male"],
    ageGroup: ["18-25"],
    moods: ["Fresh", "Sporty"],
    outfit: ["Casual"],
    season: ["Summer"],
    time: ["Afternoon"],
    intensity: "Light",
    occasions: ["Casual Outing"],
    notes: "Ginger, lavender, wood",
    longevity: "Moderate",
    sillage: "Soft",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400"
  },
  {
    id: 92,
    name: "YSL Libre",
    brand: "YSL",
    gender: ["Female"],
    ageGroup: ["26-35"],
    moods: ["Bold", "Elegant"],
    outfit: ["Formal"],
    season: ["Autumn"],
    time: ["Night"],
    intensity: "Medium",
    occasions: ["Event"],
    notes: "Lavender, vanilla, musk",
    longevity: "Long",
    sillage: "Moderate",
    image: "https://images.unsplash.com/photo-1618498082443-616165d8f3c4?w=400"
  },
  {
    id: 93,
    name: "Burberry Hero",
    brand: "Burberry",
    gender: ["Male"],
    ageGroup: ["26-35"],
    moods: ["Elegant", "Fresh"],
    outfit: ["Formal"],
    season: ["Spring", "Autumn"],
    time: ["Afternoon"],
    intensity: "Medium",
    occasions: ["Professional"],
    notes: "Bergamot, juniper, cedar",
    longevity: "Moderate",
    sillage: "Moderate",
    image: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=400"
  },
  {
    id: 94,
    name: "Clinique Happy",
    brand: "Clinique",
    gender: ["Female"],
    ageGroup: ["18-25"],
    moods: ["Fresh", "Bright"],
    outfit: ["Casual"],
    season: ["Summer"],
    time: ["Morning"],
    intensity: "Light",
    occasions: ["Daily"],
    notes: "Orange, grapefruit, bergamot",
    longevity: "Moderate",
    sillage: "Soft",
    image: "https://images.unsplash.com/photo-1587017539504-67cfbddac569?w=400"
  },
  {
    id: 95,
    name: "Nishane Hacivat",
    brand: "Nishane",
    gender: ["Unisex"],
    ageGroup: ["26-35", "36-45"],
    moods: ["Elegant", "Fresh"],
    outfit: ["Formal", "Luxury"],
    season: ["Summer"],
    time: ["Afternoon"],
    intensity: "Strong",
    occasions: ["Business"],
    notes: "Pineapple, oakmoss, grapefruit",
    longevity: "Very Long",
    sillage: "Strong",
    image: "https://images.unsplash.com/photo-1600185365528-3950ca30be7a?w=400"
  },
  {
    id: 96,
    name: "Lattafa Opulent Oud",
    brand: "Lattafa",
    gender: ["Unisex"],
    ageGroup: ["26-35", "36-45"],
    moods: ["Mysterious", "Warm"],
    outfit: ["Night"],
    season: ["Winter"],
    time: ["Night"],
    intensity: "Very Strong",
    occasions: ["Special Event"],
    notes: "Oud, caramel, spices",
    longevity: "Very Long",
    sillage: "Huge",
    image: "https://images.unsplash.com/photo-1594035910387-fea47794261f?w=400"
  },
  {
    id: 97,
    name: "Zara Red Vanilla",
    brand: "Zara",
    gender: ["Female"],
    ageGroup: ["18-25"],
    moods: ["Sweet", "Romantic"],
    outfit: ["Casual", "Chic"],
    season: ["Winter"],
    time: ["Evening"],
    intensity: "Medium",
    occasions: ["Date Night"],
    notes: "Pear, vanilla, blackcurrant",
    longevity: "Moderate",
    sillage: "Moderate",
    image: "https://images.unsplash.com/photo-1525695230005-efd074980869?w=400"
  },
  {
    id: 98,
    name: "Montblanc Explorer",
    brand: "Montblanc",
    gender: ["Male"],
    ageGroup: ["26-35"],
    moods: ["Fresh", "Adventurous"],
    outfit: ["Street"],
    season: ["Spring", "Summer"],
    time: ["Afternoon"],
    intensity: "Medium",
    occasions: ["Outdoor"],
    notes: "Bergamot, vetiver, patchouli",
    longevity: "Long",
    sillage: "Moderate",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400"
  },
  {
    id: 99,
    name: "Burberry Touch for Women",
    brand: "Burberry",
    gender: ["Female"],
    ageGroup: ["18-25", "26-35"],
    moods: ["Soft", "Clean"],
    outfit: ["Casual"],
    season: ["Spring"],
    time: ["Morning"],
    intensity: "Light",
    occasions: ["Daily"],
    notes: "Peach, jasmine, cedar",
    longevity: "Moderate",
    sillage: "Soft",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400"
  },
  {
    id: 100,
    name: "Chanel Allure Homme Sport",
    brand: "Chanel",
    gender: ["Male"],
    ageGroup: ["26-35"],
    moods: ["Fresh", "Sporty"],
    outfit: ["Athletic"],
    season: ["Summer"],
    time: ["Morning"],
    intensity: "Medium",
    occasions: ["Daily"],
    notes: "Mandarin, tonka bean, musk",
    longevity: "Long",
    sillage: "Moderate",
    image: "https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?w=400"
  },

];

// FINAL EXPORT
export default perfumes;


